#!/usr/bin/python

import sys

if len(sys.argv) < 5:
    print "less number of args"
    exit(-1)


print "File arg is as "
with open(sys.argv[1],'r') as temp1:
    for x in temp1:
        print x

print "Integer arg is as "

print str(sys.argv[2])

print "Float arg is as "

print str(sys.argv[3])

print "String arg is as "

print str(sys.argv[4])

print "End of the program"
